@startuml Web訪問者システムクラス図
skinparam classAttributeIconSize 0
hide circle
 
class 訪問者 {
-ユーザID
-パスワード
-名前
-学校・所属
-メールアドレス
-電話番号
-年齢
+自分の情報を登録する()
+自分と他の人の情報を参照する()
+自分の情報を変更する()
+自分の情報を削除する()
+ログインする()
+ログアウトする()
}
 
@enduml
 