@startuml Web_visitor
skinparam  ComponentFontStyle rectange 

' 訪問者
[訪問者] o-- [ユーザーID]
[訪問者] o-- [パスワード]
[訪問者] o-- [名前]
[訪問者] o-- [学校名]
[訪問者] o-- [所属名]
[訪問者] o-- [メールアドレス]
[訪問者] o-- [電話番号]
[訪問者] o-- [年齢]
[訪問者] o-- [登録情報]
' 登録情報
[登録情報] o-- [自分]
[登録情報] o-- [他の人]
' 自分が出来ること
[自分] o-- [変更]
[自分] o-- [削除]
@enduml