@startuml 
skinparam ClassAttributeIconSize 0 

class Robodog {
-名前
-時刻
-午前の挨拶
-午後の挨拶
-夜の挨拶
-1つ目の整数
-2つ目の整数
-足し算結果

 +名前を取得()
 +名前を変更()
 +時刻を設定()
 +時刻に応じた挨拶の言葉を取得()
 +2つの整数を設定()
 +足し算結果を登録()
 +足し算結果を取得()
}
@enduml