@startuml
skinparam componentStyle rectangle
 
[会員] o-- [学生証・職員証]
[会員] o-- [貸し出し予約]
[会員] o-- [貸し出し日]
[会員] o-- [最大貸し出し冊数]
[会員] o-- [図書]

[図書] o-- [管理番号]
[図書] o-- [書名]
[図書] o-- [区分(書籍/雑誌)]
[図書] o-- [予約]

[予約] -- [返却日] 
[予約] -- [予約日] : 借りる 予約する
@enduml