@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle
 
class RoboDog {
-myName : String
-myTime :int
-goodMorning :int
-goodAfternoon :String
-goodNight : String
-firstValue : int
-secondValue : int
-result : int
 
+getMyName() : String
+setMyName() : int
+setNewTime() : void
+getMyGreeting() : String
+setTwoValues() : void
+setAndGetResult() : int
}
 
@enduml
 